### PR TITLE
Constants and errors

### LINKED ISSUE #37: parser_str
this is the reason we fail on all the string tests at the moment with the extra quotes in the ast output.

Before we concatenate we need to parse each one and determine the mode

Most/all of the skulpt code for parsing a string can be used here.

see `parse_str.c` for cpython's implementation

### PR DESCRIPTION
**Pull request by s-cork**
Some initial ideas for how to do Raise

addresses #45

close #37

### CODE REVIEW

File: src/ast/errors.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+export class pyExc extends Error {
+    static _name = "Exception";
+    args: [string, ...any[]];
+    constructor(...args: [string, ...any[]]) {
+        super(args[0]);
+        this.args = args;
+    }
+    get [Symbol.toStringTag]() {
+        return (this.constructor as typeof pyExc)._name;
+    }
```
Comment (s-cork) [inline src/ast/errors.ts:15]: again similar approach here maybe for converting to a python exception - could do a test in `ExternalError`

File: src/parser/generated_parser.ts [hunk 2]
```diff
@@ -2497,7 +2497,7 @@ export class GeneratedParser extends Parser {
         }
         this.reset(mark);
         if ((keyword = this.expect("__peg_parser__"))) {
-            return RAISE_SYNTAX_ERROR("You found it!");
+            return pegen.raise_error(this, pySyntaxError, "You found it!");
```
Comment (s-cork) [inline src/parser/generated_parser.ts:2500]: maybe `raise_error` and `raise_error_at_known_location` should really be on the `Parser`
so that we can call
`this.raise_error` without having to pass this as the first argument.

File: src/parser/generated_parser.ts [hunk 3]
```diff
@@ -3383,7 +3387,13 @@ export class GeneratedParser extends Parser {
             (literal = this.expect(",")) &&
             ((opt = this._tmp_125()), 1)
         ) {
-            return RAISE_SYNTAX_ERROR_KNOWN_LOCATION(a, "Generator expression must be parenthesized");
+            return pegen.raise_error_known_location(
+                this,
+                pySyntaxError,
+                a.lineno,
+                a.col_offset + 1,
```
Comment (s-cork) [inline src/parser/generated_parser.ts:3394]: this isn't quite correct. Sometimes `a` is an AST sometimes it's a `TokenInfo`. We could maybe add getters to `TokenInfo` for `lineno` and `col_offset`?

File: src/parser/pegen.ts [hunk 4]
```diff
@@ -467,6 +469,21 @@ export function get_expr_name(e: expr): string {
...
+    msg: string
+): never {
+    if (p.start_rule === FSTRING_INPUT) {
+        /** @todo */
+    }
+    /** @todo should we just set the error indicator and return null then check this in the memoize decorator? */
+    // p.error_indicator = 1;
+    throw new errtype(msg, ["<file>", lineno, col_offset, p.peek().string]);
+}
+
```
Comment (s-cork) [inline src/parser/pegen.ts:486]: initial implementation - as above -maybe this should live in the Parser class rather than in pegen.

File: tools/gen_parser/skulpt_parser_genarator.py [hunk 5]
```diff
@@ -136,6 +136,24 @@ def clean_type(type):
...
 
+def clean_action(action):
+    if not action.startswith("RAISE"):
+        return action
+    if action.startswith("RAISE_SYNTAX_ERROR ("):
+        return action.replace("RAISE_SYNTAX_ERROR (", "pegen.raise_error ( this, pySyntaxError,")
+    elif action.startswith("RAISE_SYNTAX_ERROR_KNOWN_LOCATION ( a"):
+        return action.replace(
+            "RAISE_SYNTAX_ERROR_KNOWN_LOCATION ( a",
+            "pegen.raise_error_known_location ( this, pySyntaxError, a.lineno, a.col_offset + 1",
```
Comment (s-cork) [inline tools/gen_parser/skulpt_parser_genarator.py:147]: similar to how Cpython uses macros for these... could also update the patch

**Comment by s-cork** [comment]
Ran 301 tests in 31.673s

FAILED (failures=48, errors=21, skipped=3)

File: src/ast/errors.ts (hunk 1 above)
Comment (s-cork) [reply src/ast/errors.ts:15]: Or maybe we can make these error types subclass the JavaScript SyntaxError. And catch them that way.

File: src/ast/constants.ts [hunk 6]
```diff
@@ -11,11 +12,15 @@ export class pyConstant<V> {
     valueOf(): V {
         return this._v;
     }
+    get [Symbol.toStringTag]() {
+        return (this.constructor as typeof pyConstant)._name;
+    }
```
[the remark this answers is not in the document]
Comment (albertjan) [reply src/ast/constants.ts:17]: where `const` is an array of our parser constant types?

File: src/parser/generated_parser.ts (hunk 2 above)
Comment (albertjan) [reply src/parser/generated_parser.ts:2500]: this is true for the whole of pegen.ts

File: src/parser/pegen.ts (hunk 4 above)
Comment (albertjan) [reply src/parser/pegen.ts:486]: does it live in pegen in cpython?

Comment (s-cork) [reply src/parser/pegen.ts:486]: it does, but then so do a lot of things like - `this.expect` and `this.number`...

File: src/parser/generated_parser.ts (hunk 2 above)
Comment (s-cork) [reply src/parser/generated_parser.ts:2500]: yes - but I think we actually need `this` here where as I think for all the functions we've written so far we haven't used the `p` argument.

File: src/ast/constants.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (s-cork) [reply src/ast/constants.ts:17]: I don't know why I used const.

I meant

```javascript
case astnodes.Constant:
    const value = node.value;
    switch (value[Symbol.toStringTag]) {
        case "str":
            // ...
```

**Comment by s-cork** [comment]
Ran 356 tests in 37.094s

FAILED (failures=54, errors=1, skipped=2)

File: src/parser/generated_parser.ts [hunk 7]
```diff
@@ -1,12 +1,10 @@
 // @generated by pegen from ../cpython/Grammar/python.gram
 // deno-lint-ignore-file no-explicit-any camelcase no-unused-vars
-// @ts-nocheck
```
Comment (s-cork) [inline src/parser/generated_parser.ts:3]: managed to remove the ts-nocheck 😉

File: src/parser/generated_parser.ts (hunk 2 above)
Comment (albertjan) [reply src/parser/generated_parser.ts]: https://twitter.com/ajpnijburg/status/1408732658037923843?s=20

File: src/parser/generated_parser.ts (hunk 7 above)
Comment (albertjan) [reply src/parser/generated_parser.ts:3]: amazing!

File: src/parser/generated_parser.ts (hunk 2 above)
Comment (s-cork) [reply src/parser/generated_parser.ts]: Oh very interesting - great use of Twitter. What does that mean for us do you think?

(I think it means we've got it right with `name`, `expect` etc)

(And we still need to work out `fill_token` does for us).

**Comment by s-cork** [comment]
Do you want me to do a quick rebase?

File: src/parser/pegen.ts [hunk 8]
```diff
@@ -1983,8 +1989,12 @@ export function get_names(p: Parser, names_with_defaults: NameDefaultPair[] | nu
...
 // }
+type exprOrNull<T> = T extends NameDefaultPair<infer R> ? (R extends expr ? R : expr | null) : expr | null;
 
-export function get_defaults(p: Parser, names_with_defaults: NameDefaultPair[]): exprOrNone[] {
+export function get_defaults<T extends NameDefaultPair<exprOrNull<T>>>(
+    p: Parser,
+    names_with_defaults: T[]
+): exprOrNull<T>[] {
     return names_with_defaults.map((pair) => pair.value);
 }
```
Comment (s-cork) [inline src/parser/pegen.ts:2000]: This also was 🤯 for me... It means that typescript knows if you're passing a nameDefaultPare with `expr` only values or `expr | null` values. (kw_defaults have `expr | null`, defaults have only `expr`).

File: src/parser/generated_parser.ts (hunk 2 above)
Comment (albertjan) [reply src/parser/generated_parser.ts]: from several expeditions down the `fill_token` rabbit hole, I think the most important thing for us is finding `# type: ignore` comments
